#! /c/Users/oyino/Documents/devsearch/honey/Scripts/python

1.
def calculate (num1, num2=4):
  res = num1 * num2
  print(res)


if __name__=="__main__":
    calculate(5, 6)  

var = "James" * 2  * 3
print(var)

# result = 30

2.
var = "James" * 2  * 3
print(var)

# result = JamesJamesJamesJamesJamesJames

3.
x = 36 / 4 * (3 +  2) * 4 + 2
print(x)

# result = 182.0

4.
var1 = 1
var2 = 2
var3 = "3"

print(var1 + var2 + var3)

# result = error = int cannot be added to string

5.
p, q, r = 10, 20 ,30
print(p, q, r)

# result = 10 20 30
