# False	await		else		import	
# None	break		except		in	
# True	class		finally		is	
# and	continue	for			try
# as	def			non			while
# assert del			not			lambda
# async	elif		if			yield
# from	global		or			local
# with	raise		return		pass
